package ru.turlyunef.focusstart.turlyun.common;

public enum MessageType {
    CLIENT_MESSAGE,
    CLIENT_NAME_REQUEST,
    CLIENT_NAME_RESPONSE,
    CLIENT_NAMES_REQUEST,
    CLIENT_NAMES_RESPONSE,
    WRONG_CLIENT_NAME,
    SUCCESS_CONNECT,
    NEW_CLIENT_CONNECTED,
    CLIENT_DISCONNECTED
}